# Don't use tabs in configuration files

# Default YAML frontmatter settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      gamla_disqus_satte: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      
# Setup
title:               Joey
tagline:             "an uxer blog"
description:         "Chinese is my second language, first is you."
url:                 http://joeyqiang.me
baseurl:             ""
excerpt_separator:   "<!--more-->"
paginate:            3
paginate_path:       "/blog/page:num/"
exclude:             ["README.md","LICENSE"]
permalink:           pretty
relative_permalinks: true

# Markdown
markdown:            redcarpet
highlighter:         pygments
redcarpet:
  extensions:        ["footnotes","quote","highlight","superscript","space_after_headers","lax_spacing","fenced_code_blocks","no_intra_emphasis","tables", "autolink", "strikethrough", "with_toc_data"]
  
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:             compressed
  
# About/contact
author:
  name:              Joey
  url:               http://www.jianshu.com/users/eefbf767d583/latest_articles
  email:             joeyqiang@gmail.com

# Custom vars
version:             1.1.0
