# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Joey
tagline:             'an uxer'
description:         'Chinese is only my second language, you are my first one.'
url:                 http://joeyqiang.me
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Joey
  url:               https://twitter.com/mdo
  email:             joeyqiang@gmail.com

# Custom vars
version:             1.0.0
